### ISSUE TITLE
Curious about Call Stack Info in Your Project 😊

### ISSUE THREAD

**Issue by NiceAsiv** [CGCL-codes/MavenEcoSysResearch#2]
Hello！Thanks a bunch for your hard work and for sharing your project with the community!
I am currently working on a similar project and I am curious about how you obtained the call stack information in your research. Could you please provide more details about the methods or tools you used to collect the call stack data?
Any insights or guidance you could offer would be greatly appreciated.

**Comment by Simplewyl2000** [comment]
Thanks for your appreciation!

The call stack(or we can call it call chain since call stack sounds more like a function call stack during **dynamic execution**, however here we mean to refer to the call chain along the **static** call graph), is obtained by doing reachability analysis from the downstream call site(sites where downstream call upstream API) to the vulnerable API using the call graph of the vulnerable upstream.

We use [Soot](https://github.com/soot-oss/soot) to build the call graph, but you can try [JavaCG](https://github.com/gousiosg/java-callgraph) as well, which I think is more user-friendly compared with Soot.

Any other questions are welcome~

**Comment by NiceAsiv** [comment]
Thank you very much for your reply, it has been incredibly helpful. Currently, I am also using Soot's call graph for reachability analysis, but I have to specify the entry classes each time to find the desired paths. However, I am looking to identify paths where the starting method is unknown but the endpoint method is known. In such cases, I end up having to iterate through all application classes, which is not very efficient. Therefore, I considered using the BACKWARDICFG graph for analysis, but this approach is also limited by the entry classes. If I don't know the entry class, I am unable to find a viable path.
Once again, I would like to express my gratitude for your assistance.(^～^)

**Comment by Simplewyl2000** [comment]
Yes, you are right, you have to specify the entry class(Or the entry method? I can not remember many details as it was done a long time ago) to do the reachability analysis.

What we have done is specify every **public** function as the **entry method**, then get method invocation between these methods and build the call graph. After you get the call graph, you can use some graph process utilities like networkx(a Python package, I chose to use Python since there are no useful graph tools in Java) to analysis the graph, like what you said, find a path/paths to your endpoint method.

Hope it can help you out~

**Comment by NiceAsiv** [comment]
Thank you for your detailed explanation—it really cleared up my confusion! I've been primarily focusing on using soot for analysis, and your approach has provided me with a great new perspective.
Thanks again for your insights, they are immensely helpful! 😊
